[tox]
requires =
    tox>=4.2
envlist =
    py{310,311}-django{52}-cms{41,50}
    py{312}-django{52,60}-cms{50}
    py{313}-django{52,60}-cms{50}

skip_missing_interpreters=True

[flake8]
max-line-length = 119
exclude =
    *.egg-info,
    .eggs,
    .git,
    .settings,
    .tox,
    build,
    data,
    dist,
    docs,
    *migrations*,
    requirements,
    tmp

[isort]
line_length = 79
skip = manage.py, *migrations*, .tox, .eggs, data
include_trailing_comma = true
multi_line_output = 5
not_skip = __init__.py
lines_after_imports = 2
default_section = THIRDPARTY
sections = FUTURE, STDLIB, DJANGO, CMS, THIRDPARTY, FIRSTPARTY, LIB, LOCALFOLDER
known_first_party = djangocms_snippet
known_cms = cms, menus
known_django = django

[testenv]
commands =
    {envpython} --version
    {env:COMMAND:coverage} run -m pytest
deps =
    -r tests/requirements/{env_name}.txt
package = wheel
set_env =
    PYTHONDEVMODE = 1
