[tox]
requires =
    tox>=4.2
envlist =
    py{310,311}-django{52}-cms{41,50}
    py312-django52-cms41
    py{312}-django{52,60}-cms{50,51alpha1}
    py{313}-django{52,60}-cms{50,51alpha1}

skip_missing_interpreters=True

[testenv]
commands =
    {envpython} --version
    {env:COMMAND:coverage} run -m pytest
deps =
    -r tests/requirements/{env_name}.txt
package = wheel
set_env =
    PYTHONDEVMODE = 1
