# Generated by Django 1.9 on 2018-10-12 10:03
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_snippet', '0007_auto_alter_template_helptext'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snippetptr',
            options={'verbose_name': 'Snippet Ptr', 'verbose_name_plural': 'Snippet Ptrs'},
        ),
    ]
