# Generated by Django 2.2.24 on 2021-08-31 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_snippet', '0008_auto_change_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnippetGrouper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='snippet',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='slug',
            field=models.SlugField(default='', max_length=255, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='snippet',
            name='snippet_grouper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='djangocms_snippet.SnippetGrouper'),
        ),
        migrations.AddField(
            model_name='snippetptr',
            name='new_snippet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djangocms_snippet.SnippetGrouper'),
        ),
    ]
