# Generated by Django 2.2.24 on 2021-08-31 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_snippet', '0009_auto_20210831_0715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippetptr',
            name='snippet',
        ),
    ]
