# Generated by Django 2.2.24 on 2021-08-31 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_snippet', '0010_remove_snippetptr_snippet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippetptr',
            old_name='new_snippet',
            new_name='snippet',
        ),
    ]
