# Generated by Django 2.2.24 on 2021-09-07 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_snippet', '0011_cms4_plugin_data_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippetptr',
            name='snippet',
        ),
    ]
