# Generated by Django 4.2.11 on 2024-03-13 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0034_remove_pagecontent_placeholders'),
        ('djangocms_snippet', '0012_auto_20210915_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippetptr',
            name='cmsplugin_ptr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin'),
        ),
    ]
