# Generated by Django 2.2.24 on 2021-10-19 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_snippet', '0013_auto_20210915_0751'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snippet',
            options={'verbose_name': 'Snippet', 'verbose_name_plural': 'Snippets'},
        ),
    ]
