# Generated by Django 2.2.24 on 2021-09-15 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_snippet', '0008_auto_change_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnippetGrouper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='snippet',
            name='snippet_grouper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='djangocms_snippet.SnippetGrouper'),
        ),
        migrations.AddField(
            model_name='snippetptr',
            name='snippet_grouper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djangocms_snippet.SnippetGrouper'),
        ),
    ]
