# Generated by Django 2.2.24 on 2021-08-31 10:45
from django.db import migrations


def cms4_migration(apps, schema_editor):
    SnippetPtr = apps.get_model('djangocms_snippet', 'SnippetPtr')

    for snippet_plugin in SnippetPtr.objects.all():
        snippet = snippet_plugin.snippet
        snippet_plugin.snippet_grouper = snippet.snippet_grouper
        snippet_plugin.save()


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_snippet', '0010_cms4_grouper_version_data_migration'),
    ]

    operations = [
        migrations.RunPython(cms4_migration)
    ]
