# Generated by Django 5.0.6 on 2024-05-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("djangocms_snippet", "0014_merge_20240519_2117"),
    ]

    operations = [
    ]
